"""followers

Revision ID: 549327775703
Revises: fa4cfdfb9e0e
Create Date: 2021-04-30 12:31:39.099990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '549327775703'
down_revision = 'fa4cfdfb9e0e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
